# Generated by Django 6.1 on 2026-08-22 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted_customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_lead', to='crm.customer'),
        ),
    ]
